services:
  doteducation-mongodb:
    image: mongo:7.0.5-jammy
    attach: false
    ports:
      - 27117:27017
    networks:
      - doteducation-network

  doteducation-api:
    image: node:20.12
    ports:
      - 4000:4000
    volumes:
      - ./codebase/api:/usr/api
    env_file:
      - ./environments/.api
    command: >
      bash -c "cd /usr/api &&
        yarn &&
        yarn dev"
    depends_on:
      - doteducation-mongodb
    networks:
      - doteducation-network

  doteducation-app:
    image: node:20.12
    ports:
      - 3000:3000
    volumes:
      - ./codebase/app:/usr/app
    command: >
      bash -c "cd /usr/app &&
        yarn &&
        yarn dev"
    depends_on:
      - doteducation-api
    networks:
      - doteducation-network

  doteducation-lp:
    image: node:20.12
    ports:
      - 3001:3001
    volumes:
      - ./codebase/lp:/usr/lp
    command: >
      bash -c "cd /usr/lp &&
        yarn &&
        yarn dev"
    depends_on:
      - doteducation-app
    networks:
      - doteducation-network

networks:
  doteducation-network:
    driver: bridge
